networks:
  clearnet-tier:
    driver: bridge

services:
  red_engine:
    # CHANGE THIS: Use the local image we just compiled natively
    image: red-engine-image
    container_name: red_engine_node
    restart: unless-stopped
    userns_mode: keep-id
    networks:
      - clearnet-tier
    volumes:
      - ./data:/app/data:rw
      - ./config.json:/app/config.json:rw
      - ./contributors.json:/app/contributors.json:ro

  caddy_proxy:
    image: docker.io/library/caddy:latest
    container_name: caddy_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - clearnet-tier
    volumes:
      - ./caddy_routing:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - red_engine
    command: >
      /bin/sh -c '
      if [ ! -f /etc/caddy/Caddyfile ]; then
        echo "Generating default Caddyfile..."
        echo ":80 {" > /etc/caddy/Caddyfile
        echo "    reverse_proxy red_engine:8080" >> /etc/caddy/Caddyfile
        echo "}" >> /etc/caddy/Caddyfile
      fi;
      caddy run --config /etc/caddy/Caddyfile --adapter caddyfile'

volumes:
  caddy_data:
  caddy_config:
